### ISSUE TITLE
@IFTTT Corrigir string inteira: O sol nasce no horizonte Sally Mustang (http://ift.tt/2hqqtqn) e Júlia (http://ift.tt/2ibfksg) são os únicos sobreviventes.  Sally Mustang (http://ift.tt/2hqqtqn) se aproxima silenciosamente e aponta sua arma para a cabeça de Júlia (http://ift.tt/2ibfksg) e diz que o jogo está terminado e a justiça foi feita.  Júlia (http://ift.tt/2ibfksg) por sua vez saca rápidamente uma flecha e enfia na garganta Sally Mustang (http://ift.tt/2hqqtqn). Sally Mustang (http://ift.tt/2hqqtqn) enfia sua faca no peito do Gavião Arqueiro joga suas armas no chão e sua vida se esvai com um sorriso no rosto. Júlia (http://ift.tt/2ibfksg). Ambos morreram o dia acaba e não houve nenhum vencedor para contar história...

### ISSUE THREAD

**Issue by FernandoTBarros** [FernandoTBarros/MarvelZionWW#62]
Fernando0 em Sociedade Fenix : @IFTTT Corrigir string inteira: O sol nasce no horizonte, Sally Mustang (<a href="http://ift.tt/2hqqtqn">http://ift.tt/2hqqtqn</a>) e J&uacute;lia (<a href="http://ift.tt/2ibfksg">http://ift.tt/2ibfksg</a>) s&atilde;o os &uacute;nicos sobreviventes. Sally Mustang (<a href="http://ift.tt/2hqqtqn">http://ift.tt/2hqqtqn</a>) se aproxima silenciosamente e aponta sua arma para a cabe&ccedil;a de J&uacute;lia (<a href="http://ift.tt/2ibfksg">http://ift.tt/2ibfksg</a>), e diz que o jogo est&aacute; terminado e a justi&ccedil;a foi feita. J&uacute;lia (<a href="http://ift.tt/2ibfksg">http://ift.tt/2ibfksg</a>) por sua vez saca r&aacute;pidamente uma flecha e enfia na garganta Sally Mustang (<a href="http://ift.tt/2hqqtqn">http://ift.tt/2hqqtqn</a>). Sally Mustang (<a href="http://ift.tt/2hqqtqn">http://ift.tt/2hqqtqn</a>), enfia sua faca no peito do Gavi&atilde;o Arqueiro, joga suas armas no ch&atilde;o e sua vida se esvai com um sorriso no rosto. J&uacute;lia (<a href="http://ift.tt/2ibfksg">http://ift.tt/2ibfksg</a>). Ambos morreram, o dia acaba e n&atilde;o houve nenhum vencedor para contar hist&oacute;ria...

**Comment by faberoso** [comment]
ACERTEI MIZERAVI
