### ISSUE TITLE
@IFTTT reduzir o timer de duração do dia

### ISSUE THREAD

**Issue by FernandoTBarros** [FernandoTBarros/MarvelZionWW#73]
Faberoso em Sociedade Fenix : @IFTTT reduzir o timer de dura&ccedil;&atilde;o do dia

**Comment by faberoso** [comment]
TÁ SERTO!

**Comment by FernandoTBarros** [comment]
@faberoso não tava certo essa aqui não tava? não é pra reduzir msm o timer? hoje tá padrão 60
